"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.11.16.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from mysite.secrets import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CONSUMER_KEY = "3MVG9fTLmJ60pJ5KZX5.J.REVzFjkEF3dxZu6YU2KHXhT3NBxCCGNNl2SundhN1RwplN7EHGXTfp0k7jY2ZXl"
CONSUMER_SECRET = "47483693821357081"
USER = "amolone4@gradproject.com"
PASSWORD = "iJKhuYuAGEemP34yydCCU9PaM9uvG4w5cDEt6xoSmqNymaQgVPst6oNbQzb5Sc9ERvo22ARWGvfXmh8vVevvFucx4Pkxnc87uDJtudTBj4Yt8UAsjPJ6B5W7hnXTKUG6thynGAo6haEUewzHskwWqaBNAmKvEsfnqzrDFr4NCXur6AVUv9z9MGVUqmsuYfgV36GUpPHRVNntyWVWWUg4h8gNEspZCHcBJu8hRQvmhKLHDtbaJZTS45Kaq8rnc3cw"
SECURITY_TOKEN="hRuqS5gpzpiKEpYy6lVGEFhs"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 's0c&e^vhl6lk3v7==#3=xt6_!1#=!%jyls&@owm&ada7r#@=u&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'salesforce',
    'poolTool',
    'djng',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'salesforce': {
        'ENGINE': 'salesforce.backend',
        'CONSUMER_KEY': CONSUMER_KEY,
        'CONSUMER_SECRET': CONSUMER_SECRET,
        'USER': USER,
        'PASSWORD': PASSWORD,
        'HOST': 'https://login.salesforce.com',
    }

}

DATABASE_ROUTERS = [
    "salesforce.router.ModelRouter"
]

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

FORM_RENDERER = 'djng.forms.renderers.DjangoAngularBootstrap3Templates'

STATIC_ROOT = ''

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    ('node_modules', os.path.join(BASE_DIR, 'node_modules')),
    (os.path.join('static'))
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
